version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  web:
    image: moumou200/express-app-sample:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    ports:
      - "3000:3000"
    secrets:
      - db_host
      - db_user
      - db_password
      - db_name
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: mydatabase
    depends_on:
      - db
    networks:
      - webnet

secrets:
  db_host:
    external: true
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true

volumes:
  db_data:

networks:
  webnet:
    driver: overlay

